### ISSUE TITLE
How about add CODE_OF_CONDUCT.md to flip?

### ISSUE THREAD

**Issue by bbvch13531** [xxxnell/flip#18]
Type of issue
 - Doc

Description
- I think opensource project should have code of conduct. How about add CODE_OF_CONDUCT.md to flip?
You could add CODE_OF_CONDUCT.md below [link](https://github.com/xxxnell/flip/community/code-of-conduct/new) 😄

**Comment by xxxnell** [comment]
Thank you for your good suggestion.

`CODE OF CONDUCT` is useful in some cases, but I think this project is unnecessary at this moment for the following reasons:

* If this project is operating an instant chat room like gitter and IRC, It can happen that someone is often harassing an individual. However, this project does not have a community messaging yet.
* Adding unnecessary documentation to a project is a burden to maintain and review the project.
* The community is not large enough to define and operate appropriate codes of conduct. On the other hand, some clauses of code of conduct, including sexism and rasicsm discrimination, are self-explanatory.

So, I did not intentionally include `CODE OF CONDUCT` in this project. Of course, I and this community are dedicated to providing a harassment-free community for everyone. If you have any other comments, please leave more.

Thank you for your contribution again.

**Comment by bbvch13531** [comment]
Thank you for kindness answer. I close issue myself.
I'm totally agree to your resonable consideration. I hope I could contribute to flip soon. Maybe I'll send another issue related to Docs. Does it looks good on you?

**Comment by xxxnell** [comment]
Contribution to the documentation is definitely helpful. I look forward to your contribution. :+1:

**Comment by xxxnell** [comment]
Contribution to the documentation is definitely helpful. I look forward to your contribution. 👍
